# Generated by Django 4.2.16 on 2024-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='logged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='open_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
