# Generated by Django 4.2.16 on 2024-09-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
    ]
